package com.github.wdeqin.flyit.world.dao;

import com.github.wdeqin.flyit.world.model.CityTest;

public interface CityTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_test
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_test
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    int insert(CityTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_test
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    int insertSelective(CityTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_test
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    CityTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_test
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    int updateByPrimaryKeySelective(CityTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_test
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    int updateByPrimaryKey(CityTest record);
}