package com.github.wdeqin.flyit.world.dao;

import com.github.wdeqin.flyit.world.model.TestPlan;

public interface TestPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_plan
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_plan
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    int insert(TestPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_plan
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    int insertSelective(TestPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_plan
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    TestPlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_plan
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    int updateByPrimaryKeySelective(TestPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_plan
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    int updateByPrimaryKey(TestPlan record);
    
    TestPlan selectOneStatusForUpdate(String status);
}