package com.github.wdeqin.flyit.world.model;

public class CityTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_test.id
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_test.name
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_test.country_code
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    private String countryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_test.population
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    private Integer population;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_test.id
     *
     * @return the value of city_test.id
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_test.id
     *
     * @param id the value for city_test.id
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_test.name
     *
     * @return the value of city_test.name
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_test.name
     *
     * @param name the value for city_test.name
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_test.country_code
     *
     * @return the value of city_test.country_code
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_test.country_code
     *
     * @param countryCode the value for city_test.country_code
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_test.population
     *
     * @return the value of city_test.population
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    public Integer getPopulation() {
        return population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_test.population
     *
     * @param population the value for city_test.population
     *
     * @mbggenerated Sun Jul 03 09:49:25 CST 2016
     */
    public void setPopulation(Integer population) {
        this.population = population;
    }
}