package com.github.wdeqin.flyit.world.model;

import java.util.Date;

public class TestPlan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_plan.id
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_plan.name
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_plan.status
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_plan.class_name
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_plan.concurrency
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    private Byte concurrency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_plan.op_size
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    private Long opSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_plan.key_num_1
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    private Long keyNum1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_plan.key_num_2
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    private Long keyNum2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_plan.key_num_3
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    private Long keyNum3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_plan.key_char_1
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    private String keyChar1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_plan.key_char_2
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    private String keyChar2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_plan.key_char_3
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    private String keyChar3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_plan.creation_date
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_plan.creation_time
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    private Date creationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_plan.update_date
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_plan.update_time
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_plan.id
     *
     * @return the value of test_plan.id
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_plan.id
     *
     * @param id the value for test_plan.id
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_plan.name
     *
     * @return the value of test_plan.name
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_plan.name
     *
     * @param name the value for test_plan.name
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_plan.status
     *
     * @return the value of test_plan.status
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_plan.status
     *
     * @param status the value for test_plan.status
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_plan.class_name
     *
     * @return the value of test_plan.class_name
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_plan.class_name
     *
     * @param className the value for test_plan.class_name
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_plan.concurrency
     *
     * @return the value of test_plan.concurrency
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public Byte getConcurrency() {
        return concurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_plan.concurrency
     *
     * @param concurrency the value for test_plan.concurrency
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public void setConcurrency(Byte concurrency) {
        this.concurrency = concurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_plan.op_size
     *
     * @return the value of test_plan.op_size
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public Long getOpSize() {
        return opSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_plan.op_size
     *
     * @param opSize the value for test_plan.op_size
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public void setOpSize(Long opSize) {
        this.opSize = opSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_plan.key_num_1
     *
     * @return the value of test_plan.key_num_1
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public Long getKeyNum1() {
        return keyNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_plan.key_num_1
     *
     * @param keyNum1 the value for test_plan.key_num_1
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public void setKeyNum1(Long keyNum1) {
        this.keyNum1 = keyNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_plan.key_num_2
     *
     * @return the value of test_plan.key_num_2
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public Long getKeyNum2() {
        return keyNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_plan.key_num_2
     *
     * @param keyNum2 the value for test_plan.key_num_2
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public void setKeyNum2(Long keyNum2) {
        this.keyNum2 = keyNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_plan.key_num_3
     *
     * @return the value of test_plan.key_num_3
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public Long getKeyNum3() {
        return keyNum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_plan.key_num_3
     *
     * @param keyNum3 the value for test_plan.key_num_3
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public void setKeyNum3(Long keyNum3) {
        this.keyNum3 = keyNum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_plan.key_char_1
     *
     * @return the value of test_plan.key_char_1
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public String getKeyChar1() {
        return keyChar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_plan.key_char_1
     *
     * @param keyChar1 the value for test_plan.key_char_1
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public void setKeyChar1(String keyChar1) {
        this.keyChar1 = keyChar1 == null ? null : keyChar1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_plan.key_char_2
     *
     * @return the value of test_plan.key_char_2
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public String getKeyChar2() {
        return keyChar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_plan.key_char_2
     *
     * @param keyChar2 the value for test_plan.key_char_2
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public void setKeyChar2(String keyChar2) {
        this.keyChar2 = keyChar2 == null ? null : keyChar2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_plan.key_char_3
     *
     * @return the value of test_plan.key_char_3
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public String getKeyChar3() {
        return keyChar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_plan.key_char_3
     *
     * @param keyChar3 the value for test_plan.key_char_3
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public void setKeyChar3(String keyChar3) {
        this.keyChar3 = keyChar3 == null ? null : keyChar3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_plan.creation_date
     *
     * @return the value of test_plan.creation_date
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_plan.creation_date
     *
     * @param creationDate the value for test_plan.creation_date
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_plan.creation_time
     *
     * @return the value of test_plan.creation_time
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_plan.creation_time
     *
     * @param creationTime the value for test_plan.creation_time
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_plan.update_date
     *
     * @return the value of test_plan.update_date
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_plan.update_date
     *
     * @param updateDate the value for test_plan.update_date
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_plan.update_time
     *
     * @return the value of test_plan.update_time
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_plan.update_time
     *
     * @param updateTime the value for test_plan.update_time
     *
     * @mbggenerated Sun Jul 03 11:09:08 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}